version: '3'
services:
  backend-mongo:
    image: mongo:5
    container_name: db_mongo
    environment:
      MONGODB_DATABASE: ${DB_NAME}
    restart: always
    volumes:
      # Montamos un volumen para Mongo para no perder los datos de bd
      - ./mongo:/data/db
    ports:
      - 27017:27017