version: '3'
services:
  backend-mongo:
    image: mongo:5
    environment:
      MONGODB_DATABASE: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    restart: always
    volumes:
      # Montamos un volumen para Mongo para no perder los datos de bd
      - ./mongo:/data/db
    ports:
      - ${DB_PORT}:27017